plugins {
    id "maven-publish"
}

publishing{
// publish to github packages
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://github.com/DOI-BOR/WTMP-W2-Executables")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}