plugins {
    id "wtmp.deps-conventions"
    id "wtmp.java-conventions"
    id "wtmp.publishing-conventions"
    id "wtmp.versioning-conventions"
}

allprojects {
    group = "edu.pdx.ce.w2"
}


def exeDir = file("dist")
def executables = [
        [
                artifactId: "w2",
                version   : "4.0-win-x86_64",
                file      : new File(exeDir, "w2-4.0-win-x86_64.exe")
        ],
        [
                artifactId: "w2-pre",
                version   : "4.0-win-x86_64",
                file      : new File(exeDir, "w2-pre-4.0-win-x86_64.exe")
        ],
        [
                artifactId: "w2-post",
                version   : "3.0-win-x86_64",
                file      : new File(exeDir, "w2-post-3.0-win-x86_64.exe")
        ],
        [
                artifactId: "w2-pre-console",
                version   : "4.5-win-x86_64",
                file      : new File(exeDir, "w2-pre-console-4.5-win-x86_64.exe")
        ],
        [
                artifactId: "w2",
                version   : "4.1-TCD-mp-win-x86_64",
                file      : new File(exeDir, "w2-4.1-TCD-mp-win-x86_64.exe")
        ],
        [
                artifactId: "w2",
                version   : "4.5-64-Folsom",
                file      : new File(exeDir, "w2-4.5-64-Folsom.exe")
        ],
        [
                artifactId: "w2",
                version   : "4.5-win-x86_64",
                file      : new File(exeDir, "w2-4.5-win-x86_64.exe")
        ],
        [
                artifactId: "w2",
                version   : "TCD-081721",
                file      : new File(exeDir, "w2-TCD-081721.exe")
        ],
        [
                artifactId: "w2-pre",
                version   : "4.5-win-x86_64",
                file      : new File(exeDir, "w2-pre-4.5-win-x86_64.exe")
        ],
        [
                artifactId: "w2",
                version   : "4.1-TCD-d7-win-x86_64",
                file      : new File(exeDir, "w2-4.1-TCD-d7-win-x86_64.exe")
        ],
        [
                artifactId: "w2",
                version   : "v5-tcd-2025-09-26",
                file      : new File(exeDir, "w2-v5-tcd-2025-09-26.exe")
        ]
]


publishing {
    publications {

        mavenJava(MavenPublication) {
            from components.java
            groupId = "edu.pdx.ce.w2"
            artifactId = "wtmp-w2-executables"
            version = "0.0"
        }


        // One MavenPublication per executable
        executables.each { exe ->
            create("${exe.artifactId}-${exe.version}", MavenPublication) {
                groupId    = project.group
                artifactId = exe.artifactId
                version    = exe.version

                // Primary Maven artifacts: stub JAR + POM (required by Maven repos)
                from components.java

                // Attach the EXE as an additional classifier artifact
                artifact(exe.file) {
                    classifier = "exe"  // consumers will reference :exe@exe
                    extension  = "exe"
                }
            }
        }
    }
}

